--------------------------------------------------------
--  File created - Friday-May-10-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "TABLE_1"."MEMBER" 
   (	"MEMBER_ID" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"CONTACT" VARCHAR2(50 BYTE), 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TABLE_1.MEMBER
SET DEFINE OFF;
Insert into TABLE_1.MEMBER (MEMBER_ID,NAME,EMAIL,CONTACT,USERNAME,PASSWORD) values (2,'rishad','rishad_rizwan_rrr@yahoo.com','01713186105','rrr','827ccb0eea8a706c4c34a16891f84e7b');
Insert into TABLE_1.MEMBER (MEMBER_ID,NAME,EMAIL,CONTACT,USERNAME,PASSWORD) values (1,'sujon','sujon335@yahoo.com','01673941126','sujon335','81dc9bdb52d04dc20036dbd8313ed055');
--------------------------------------------------------
--  DDL for Index MEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE_1"."MEMBER_PK" ON "TABLE_1"."MEMBER" ("MEMBER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("CONTACT" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."MEMBER" ADD CONSTRAINT "MEMBER_PK" PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TABLE_1"."MEMBER" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
