--------------------------------------------------------
--  File created - Friday-May-10-2013   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOOKING_DATA
--------------------------------------------------------

  CREATE TABLE "TABLE_1"."BOOKING_DATA" 
   (	"ID" NUMBER, 
	"BOOK_ID" NUMBER, 
	"MEMBER_ID" NUMBER, 
	"BOOKING_DATE" DATE, 
	"FINISHING_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into TABLE_1.BOOKING_DATA
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index BOOKING_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TABLE_1"."BOOKING_DATA_PK" ON "TABLE_1"."BOOKING_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOOKING_DATA
--------------------------------------------------------

  ALTER TABLE "TABLE_1"."BOOKING_DATA" ADD CONSTRAINT "BOOKING_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "TABLE_1"."BOOKING_DATA" MODIFY ("FINISHING_DATE" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."BOOKING_DATA" MODIFY ("BOOKING_DATE" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."BOOKING_DATA" MODIFY ("MEMBER_ID" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."BOOKING_DATA" MODIFY ("BOOK_ID" NOT NULL ENABLE);
  ALTER TABLE "TABLE_1"."BOOKING_DATA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BOOKING_DATA
--------------------------------------------------------

  ALTER TABLE "TABLE_1"."BOOKING_DATA" ADD CONSTRAINT "BOOKING_DATA_BOOK_FK1" FOREIGN KEY ("BOOK_ID")
	  REFERENCES "TABLE_1"."BOOK" ("BOOK_ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "TABLE_1"."BOOKING_DATA" ADD CONSTRAINT "BOOKING_DATA_MEMBER_FK1" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "TABLE_1"."MEMBER" ("MEMBER_ID") ON DELETE CASCADE ENABLE;
